# Generated by Django 2.1.2 on 2018-12-13 03:42

import account_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_auto_20181102_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weiboId', models.IntegerField()),
                ('userName', models.CharField(max_length=30)),
                ('comContent', models.TextField()),
                ('comDate', models.DateTimeField(auto_now_add=True)),
                ('comGood', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('fansName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='weibo',
            fields=[
                ('weiboId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('weiboDate', models.DateTimeField(auto_now_add=True)),
                ('commentNum', models.IntegerField(default=0)),
                ('goodNum', models.IntegerField(default=0)),
                ('transmitNum', models.IntegerField(default=0)),
                ('state', models.IntegerField()),
                ('transmitCon', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=account_app.models.upload_to2)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='concernsNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fansNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='headshot',
            field=models.ImageField(blank=True, default='head.png', null=True, upload_to=account_app.models.upload_to),
        ),
        migrations.AddField(
            model_name='user',
            name='weiboNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
