# Generated by Django 2.1.2 on 2018-12-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_auto_20181213_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weiboId', models.IntegerField()),
                ('userName', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='weibo',
            old_name='goodNum',
            new_name='likeNum',
        ),
        migrations.AlterField(
            model_name='weibo',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
